# Generated by Django 5.2.11 on 2026-04-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_brand_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برند ها'},
        ),
    ]
