# Generated by Django 5.2.11 on 2026-04-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_alter_productimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
