# Generated by Django 5.2.13 on 2026-06-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('popular_products', 'محصولات محبوب'), ('trending_products', 'محصولات مد')], max_length=300, null=True),
        ),
    ]
