# Generated by Django 5.2.13 on 2026-06-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('popular_products', 'محصولات محبوب'), ('trending_products', 'محصولات مد')], max_length=300, null=True, verbose_name='دسته بندی'),
        ),
    ]
