# Generated by Django 5.2.11 on 2026-04-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='image',
            field=models.ImageField(upload_to='images/banners', verbose_name='تصویر'),
        ),
    ]
