# Generated by Django 5.2.11 on 2026-04-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_sitebanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebanner',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
