# Generated by Django 5.2.13 on 2026-06-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_sitebanner_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(verbose_name='درباره ی ما')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.IntegerField(verbose_name='شماره ی تماس')),
                ('telegram_user_name', models.CharField(blank=True, null=True, verbose_name='نام کاربری تلگرام')),
                ('github_user_name', models.CharField(blank=True, null=True, verbose_name='نام کاربری گیت هاب')),
                ('linkedin_user_name', models.CharField(blank=True, null=True, verbose_name='نام کاربری لینکدین')),
                ('is_active', models.BooleanField(verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
