# Generated by Django 5.2.11 on 2026-04-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ و ساعت ساخت'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
