# Generated by Django 5.2.11 on 2026-04-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_article_create_date_time_article_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, verbose_name='اسلاگ'),
        ),
    ]
