# Generated by Django 5.2.11 on 2026-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات'),
        ),
    ]
