# Generated by Django 5.2.11 on 2026-04-05 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'کامنت مقاله', 'verbose_name_plural': 'کامنت های مقاله'},
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='مقاله'),
        ),
    ]
