# Generated by Django 5.2.13 on 2026-06-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0006_alter_articlecomment_options_articlecomment_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'کامنت مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
